### ISSUE TITLE
Tests timing out with the MSBUILDNOINPROCNODE change

### ISSUE THREAD

**Issue by MeikTranel** [jeffkl/MSBuildProjectCreator#134]
I don't know exactly whats causing this but i've narrowed a test timeout / long CI time issue down to release 6.3.1 where this change went in. the dependabot pr branch didnt even finish and i thought it was something related to github actions so i just yoinked the change in with admin powers 😂
Today i ran my test suite locally and noticed that outside of Visual Studio my tests were just skipping themselves:
![image](https://user-images.githubusercontent.com/6466560/138001280-6dd4bde0-ee46-4356-8f77-95e0e5ec2916.png)

You can see the change in finish time in the github action when the change went in:
https://github.com/MeikTranel/NXPorts/actions?query=branch%3Amaster

I tested locally and the the upgrade to 6.2.4 and 6.3.0 was fine - only after upgrading to 6.3.1 the degradation started reappearing.

I also noticed that once i SIGINT'd the dotnet test process tons of msbuild nodes still locked my test binaries (God bless LockHunter 😂)

**Comment by MeikTranel** [comment]
The nice thing about nowadays github is that you can always check if you fixed the underlying problem by releasing and watching dependabot trigger an action in my repo 😄

**Comment by jeffkl** [comment]
@MeikTranel can you please try out version [7.0.3-preview](https://www.nuget.org/packages/MSBuild.ProjectCreation/7.0.3-preview)?  I think things finally work the way I want them to, the assembly binding in these scenarios is very tricky, I'm hoping you can double check that things look good before I remove the `-preview` label.

**Comment by MeikTranel** [comment]
Sure I'll check it ASAP 😊

**Comment by MeikTranel** [comment]
Yo, looks good.
All action times and locally on VS2022 look normal.

https://github.com/MeikTranel/NXPorts/runs/4171454357?check_suite_focus=true

**Comment by jeffkl** [comment]
Awesome thanks for checking! I’ll remove the preview tag soon.
