### ISSUE TITLE
How to save a binlog for a build?

### ISSUE THREAD

**Issue by japj** [jeffkl/MSBuildProjectCreator#43]
Would it be possible to save a binlog file of a build?
This would be useful for e.g. analysis of (unittest) build failures.

**Comment by jeffkl** [comment]
Yes you'll just need to create a `ProjectCollection` and attach a `BinaryLogger`.

```C#
string binLogPath = Path.Combine(TestRootPath, "test.binlog");

using (ProjectCollection projectCollection = new ProjectCollection())
{
    projectCollection.RegisterLogger(new BinaryLogger
    {
        Parameters = $"LogFile={binLogPath}",
    });

    ProjectCreator.Templates
        .LogsMessage(
            text: "$(Property1)",
            projectCollection: projectCollection)
        .Property("Property1", "Hello World")
        .Save(GetTempFileName(".proj"))
        .TryBuild(out bool result);

        result.ShouldBeTrue();
}

File.Exists(binLogPath).ShouldBeTrue();
```

**Comment by japj** [comment]
Hi @jeffkl , thanks for this example.
Initially it seems to work ok, but I ran into some issues:

- It seems when I change the TryBuild with
   ```
   .TryBuild(out bool result, out BuildOutput buildOutput);
   ```
   then the actual binlog file that is generated seems to be corrupt.
   (it only contains "error", although the build was actually succeeded).

- Also, in this case the list of embedded msbuild files is empty.

**Comment by jeffkl** [comment]
Thanks for letting me know, turns out that's a bug.  I'm working on a fix: https://github.com/jeffkl/MSBuildProjectCreator/pull/45

**Comment by jeffkl** [comment]
Fix is published, https://github.com/jeffkl/MSBuildProjectCreator/releases/tag/v1.3.7

**Comment by japj** [comment]
Awesome! I will try it tomorrow at work and let you know if I run into anything else.

We are working on writing c# based unit tests for our custom Msbuild sdk and have been using binlog files a lot as a way of analyzing “real” build issues so want to use that too in case of test failures to help with analysis. 

When looking at some of the MSBuildSdks I realized that there were actually c# based unit tests based on this fluent api, this is greatly appreciated!

**Comment by japj** [comment]
Yes, I can indeed confirm this fixes the issue.
Again, @jeffkl thank you very much for this library and quick response!
