### ISSUE TITLE
Restore project information is not present in the binlog

### ISSUE THREAD

**Issue by japj** [jeffkl/MSBuildProjectCreator#53]
If you run a tests with binlog and do
`TryBuild(restore:true,...)` then the actual Restore information (Target execution and project files) is not present in the binlog file (only the Default build information is present).

If you do seperate Restore/Build Target it does include the correct Restore Target information, e.g. with
```c#
TryBuild("Restore",... )
TryBuild("Build",...)
```

We noticed this because we have a project that only runs in the Restore phase of the build, but did not end up in the binlog file when we use `restore:true`.

**Comment by japj** [comment]
@jeffkl thanks for the quick response! 
This bug has been driving me crazy for a while to pinpoint the scenario, but we kinda figured it out by accident when pair programming a new test case.

**Comment by japj** [comment]
@jeffkl any idea on when you expect to release a next version of the nuget package?

**Comment by jeffkl** [comment]
https://www.nuget.org/packages/MSBuild.ProjectCreation/1.4.5
